begin;

-- Synthetic leads (restricted schema), mirroring
-- tests/fixtures/synthetic-baseline.v1.json lead_scenarios 001, 002 and 005.
-- Scenarios 003 (incomplete) and 004 (duplicate) are not seeded: the
-- current restricted.leads schema does not support incomplete records
-- (name/email/phone are NOT NULL) or duplicate tracking (there is no
-- duplicate_of_id column). form_submissions and lead_consents are not
-- seeded either: the fixture has no data defined for those tables yet.
--
-- Lead codes are intentionally NOT copied from the fixture's SYN-LEAD-NNN
-- placeholders: restricted.leads.code must match the real D-09 format
-- (LED-<year>-<six-digit-sequence>) generated by
-- restricted.generate_lead_code(), so it is left to its column default
-- here rather than hardcoded.
--
-- intent_declared is a free-form text column in this migration (not
-- boolean), so the fixture's true/false values are written as the text
-- literals 'true'/'false' below.

insert into restricted.leads (
    id, name_original, name_normalized, email_original, email_normalized,
    phone_original, phone_normalized, income_range_code, income_mode,
    intent_declared, classification, status
)
values
    (
        '70000000-0000-4000-8000-000000000001',
        'Synthetic Prospect 001', lower(btrim('Synthetic Prospect 001')),
        'synthetic-prospect-001@example.invalid', lower(btrim('synthetic-prospect-001@example.invalid')),
        '+10000000001', '+10000000001',
        'income_1500000_or_more', 'individual',
        'true', 'prefiltered', 'new'
    ),
    (
        '70000000-0000-4000-8000-000000000002',
        'Synthetic Prospect 002', lower(btrim('Synthetic Prospect 002')),
        'synthetic-prospect-002@example.invalid', lower(btrim('synthetic-prospect-002@example.invalid')),
        '+10000000002', '+10000000002',
        'income_below_1500000', 'individual',
        'true', 'early', 'new'
    ),
    (
        '70000000-0000-4000-8000-000000000005',
        'Synthetic Test Prospect', lower(btrim('Synthetic Test Prospect')),
        'synthetic-test@example.invalid', lower(btrim('synthetic-test@example.invalid')),
        '+10000000005', '+10000000005',
        'income_1500000_or_more', 'complemented',
        'true', 'test', 'new'
    )
on conflict (id) do nothing;

insert into restricted.lead_deliveries (
    id, lead_id, destination_type, destination_reference, idempotency_key,
    status, attempt_count, confirmed_at, next_attempt_at
)
values
    (
        '71000000-0000-4000-8000-000000000001',
        '70000000-0000-4000-8000-000000000001',
        'synthetic_sink', 'synthetic-destination-001', 'synthetic-delivery-001',
        'pending', 0, null, null
    ),
    (
        '71000000-0000-4000-8000-000000000002',
        '70000000-0000-4000-8000-000000000002',
        'synthetic_sink', 'synthetic-destination-001', 'synthetic-delivery-002',
        'confirmed', 1, '2026-01-01T12:05:00Z'::timestamptz, null
    ),
    (
        '71000000-0000-4000-8000-000000000003',
        '70000000-0000-4000-8000-000000000005',
        'synthetic_sink', 'synthetic-destination-001', 'synthetic-delivery-003',
        'retry_scheduled', 1, null, '2026-01-01T12:10:00Z'::timestamptz
    )
on conflict (id) do nothing;

do $synthetic_seed$
begin
  raise notice
    'Synthetic seed loaded: 3 of 5 lead_scenarios and their lead_deliveries from tests/fixtures/synthetic-baseline.v1.json. Scenarios 003 (incomplete) and 004 (duplicate), plus form_submissions and lead_consents, are not yet representable/seeded (see supabase/migrations/20260727120000_personal_data_isolation_environment_separation_s1_010.sql).';
end
$synthetic_seed$;

commit;