import { randomUUID } from "node:crypto";
import {
  apiError,
  apiJson,
  databaseErrorResponse,
} from "@/lib/api/errors";
import { authorizePrivateRoute } from "@/lib/api/private-route";
import { createListHandler } from "@/lib/api/resource-routes";
import { logInfo } from "@/lib/observability/logger";

export const dynamic = "force-dynamic";

// First endpoint of the `assets` domain within S4-009 (S4-004's tables).
// private_storage_objects (S1-005) is fully server-only: unlike
// scene_generation_budgets, not even `authenticated` holds any grant on it
// (revoke all ... from public, anon, authenticated, service_role; then an
// explicit select+insert+update grant to service_role only). No human role
// can ever touch it directly, by design ("Trusted server code authorizes
// the request, uses the service role").
//
// This route is therefore a HYBRID, same shape as generation-attempts/
// route.ts, but via a direct service-role insert instead of an RPC: there
// is no "resolve" concept here (each registration is a new, non-idempotent
// row, unlike the shared per-scene budget), so context.serviceClient.from(
// "private_storage_objects").insert(...) is enough -- service_role already
// carries the exact grant S1-005 gave it, no new migration needed. The
// object stays synthetic: state stays 'registered' and storage_object_id
// stays null (no real Storage upload in this phase, matching S4-001's
// synthetic-only rule), which is the one case
// private_storage_objects_storage_link_complete permits without a real
// storage.objects row.
//
// object_key must equal `id::text || '/' || version_number::text}`
// (private_storage_objects_key_is_opaque) -- an id generated by the
// database default would not be known before the insert, so this route
// generates the id itself and computes the key from it.
//
// Once the private_storage_objects row exists, the business `assets` row
// is created through the plain userClient + RLS path: creative_owner
// (related to self), director_ai_operator (generation-type only) and
// editor (unqualified) all hold an insert policy (S4-008 Section 3);
// approver only holds UPDATE, so it is excluded from asset.write.

export const GET = createListHandler({
  table: "assets",
  listAction: "asset.read",
  createAction: "asset.write",
  requiredFields: [],
  optionalFields: [],
});

const STORAGE_REQUIRED_FIELDS = [
  "bucket_id",
  "original_name",
  "safe_name",
  "mime_type",
  "size_bytes",
  "checksum_sha256",
  "classification",
  "origin",
  "rights_basis",
] as const;

const STORAGE_OPTIONAL_FIELDS = ["rights_expires_at"] as const;

const ASSET_REQUIRED_FIELDS = ["asset_type", "rights_status"] as const;

const ASSET_OPTIONAL_FIELDS = ["license_reference"] as const;

const REQUIRED_FIELDS = [
  ...STORAGE_REQUIRED_FIELDS,
  ...ASSET_REQUIRED_FIELDS,
] as const;

const OPTIONAL_FIELDS = [
  ...STORAGE_OPTIONAL_FIELDS,
  ...ASSET_OPTIONAL_FIELDS,
] as const;

export async function POST(request: Request): Promise<Response> {
  const authorized = await authorizePrivateRoute(request, "asset.write");

  if (!authorized.ok) {
    return authorized.response;
  }

  const { context } = authorized;

  let body: unknown;

  try {
    body = await request.json();
  } catch {
    return apiError(400, "invalid_request", context.correlationId, {
      reason: "invalid_json",
    });
  }

  if (typeof body !== "object" || body === null || Array.isArray(body)) {
    return apiError(400, "invalid_request", context.correlationId, {
      reason: "object_body_required",
    });
  }

  const payload = body as Record<string, unknown>;
  const knownFields = new Set<string>([
    ...REQUIRED_FIELDS,
    ...OPTIONAL_FIELDS,
  ]);

  for (const field of Object.keys(payload)) {
    if (!knownFields.has(field)) {
      return apiError(400, "invalid_request", context.correlationId, {
        reason: "unknown_field",
        field,
      });
    }
  }

  for (const field of REQUIRED_FIELDS) {
    const value = payload[field];
    const missing =
      value === undefined ||
      value === null ||
      (typeof value === "string" && !value.trim());

    if (missing) {
      return apiError(400, "invalid_request", context.correlationId, {
        reason: "missing_field",
        field,
      });
    }
  }

  if (
    typeof payload.size_bytes !== "number" ||
    !Number.isInteger(payload.size_bytes) ||
    payload.size_bytes <= 0
  ) {
    return apiError(400, "invalid_request", context.correlationId, {
      reason: "invalid_field",
      field: "size_bytes",
    });
  }

  if (
    payload.rights_expires_at !== undefined &&
    (typeof payload.rights_expires_at !== "string" ||
      Number.isNaN(Date.parse(payload.rights_expires_at)))
  ) {
    return apiError(400, "invalid_request", context.correlationId, {
      reason: "invalid_field",
      field: "rights_expires_at",
    });
  }

  const storageObjectId = randomUUID();

  const storageRow: Record<string, unknown> = {
    id: storageObjectId,
    bucket_id: payload.bucket_id,
    object_key: `${storageObjectId}/1`,
    original_name: payload.original_name,
    safe_name: payload.safe_name,
    mime_type: payload.mime_type,
    size_bytes: payload.size_bytes,
    checksum_sha256: payload.checksum_sha256,
    owner_profile_id: context.profileId,
    classification: payload.classification,
    origin: payload.origin,
    rights_basis: payload.rights_basis,
  };

  if (payload.rights_expires_at !== undefined) {
    storageRow.rights_expires_at = payload.rights_expires_at;
  }

  const { error: storageError } = await context.serviceClient
    .from("private_storage_objects")
    .insert(storageRow)
    .select("id")
    .single();

  if (storageError) {
    return databaseErrorResponse(storageError, context.correlationId);
  }

  const assetRow: Record<string, unknown> = {
    private_storage_object_id: storageObjectId,
    asset_type: payload.asset_type,
    rights_status: payload.rights_status,
    created_by: context.profileId,
  };

  if (payload.license_reference !== undefined) {
    assetRow.license_reference = payload.license_reference;
  }

  const { data, error } = await context.userClient
    .from("assets")
    .insert(assetRow)
    .select("id")
    .single();

  if (error) {
    return databaseErrorResponse(error, context.correlationId);
  }

  logInfo({
    event: "api.resource.created",
    correlationId: context.correlationId,
    context: {
      resource: "assets",
      exercised_role: context.exercisedRole,
    },
  });

  return apiJson(
    201,
    {
      id: (data as { id: string }).id,
      private_storage_object_id: storageObjectId,
    },
    context.correlationId,
  );
}
